version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    env_file: .env
    ports:
      - "8082:8080"