version: '3.9'

services:
#  alpine:
#    build:
#      context: .
#      dockerfile: ".docker/telnet/Dockerfile"
#    tty: true
  grpc:
    container_name: "grpc"
    build:
      context: .
      dockerfile: ".docker/grpc/Dockerfile"
    ports:
      - "50051:50051"
    volumes:
      - .:/app
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - .volumes/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Secure123$
  envoy:
    build:
      context: .
      dockerfile: ".docker/envoy/Dockerfile"
    ports:
      - "8000:8000"
      - "9901:9901"
    volumes:
        - ./envoy.yaml:/etc/envoy/envoy.yaml
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    env_file: .env
    ports:
      - "8082:8080"
#  krakend:
#    image: devopsfaith/krakend:watch
#    volumes:
#      - ".docker/krakend/:/etc/krakend"
#    ports:
#      - "8080:8080"
#    command: [ "run", "-dc", "krakend.json" ]