// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	google_golang_orggrpc "google.golang.org/grpc"

	grpc "grpc/internal/infrastructure/ports/grpc/proto_gen/grpc"

	mock "github.com/stretchr/testify/mock"
)

// PromosClient is an autogenerated mock type for the PromosClient type
type PromosClient struct {
	mock.Mock
}

type PromosClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PromosClient) EXPECT() *PromosClient_Expecter {
	return &PromosClient_Expecter{mock: &_m.Mock}
}

// PromoInfo provides a mock function with given fields: ctx, in, opts
func (_m *PromosClient) PromoInfo(ctx context.Context, in *grpc.PromoInfoRequest, opts ...google_golang_orggrpc.CallOption) (*grpc.Promo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PromoInfo")
	}

	var r0 *grpc.Promo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.PromoInfoRequest, ...google_golang_orggrpc.CallOption) (*grpc.Promo, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.PromoInfoRequest, ...google_golang_orggrpc.CallOption) *grpc.Promo); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.Promo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *grpc.PromoInfoRequest, ...google_golang_orggrpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PromosClient_PromoInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoInfo'
type PromosClient_PromoInfo_Call struct {
	*mock.Call
}

// PromoInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - in *grpc.PromoInfoRequest
//   - opts ...google_golang_orggrpc.CallOption
func (_e *PromosClient_Expecter) PromoInfo(ctx interface{}, in interface{}, opts ...interface{}) *PromosClient_PromoInfo_Call {
	return &PromosClient_PromoInfo_Call{Call: _e.mock.On("PromoInfo",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *PromosClient_PromoInfo_Call) Run(run func(ctx context.Context, in *grpc.PromoInfoRequest, opts ...google_golang_orggrpc.CallOption)) *PromosClient_PromoInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]google_golang_orggrpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(google_golang_orggrpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*grpc.PromoInfoRequest), variadicArgs...)
	})
	return _c
}

func (_c *PromosClient_PromoInfo_Call) Return(_a0 *grpc.Promo, _a1 error) *PromosClient_PromoInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PromosClient_PromoInfo_Call) RunAndReturn(run func(context.Context, *grpc.PromoInfoRequest, ...google_golang_orggrpc.CallOption) (*grpc.Promo, error)) *PromosClient_PromoInfo_Call {
	_c.Call.Return(run)
	return _c
}

// PromoList provides a mock function with given fields: ctx, in, opts
func (_m *PromosClient) PromoList(ctx context.Context, in *grpc.PromoListRequest, opts ...google_golang_orggrpc.CallOption) (*grpc.PromosList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PromoList")
	}

	var r0 *grpc.PromosList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.PromoListRequest, ...google_golang_orggrpc.CallOption) (*grpc.PromosList, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.PromoListRequest, ...google_golang_orggrpc.CallOption) *grpc.PromosList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.PromosList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *grpc.PromoListRequest, ...google_golang_orggrpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PromosClient_PromoList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoList'
type PromosClient_PromoList_Call struct {
	*mock.Call
}

// PromoList is a helper method to define mock.On call
//   - ctx context.Context
//   - in *grpc.PromoListRequest
//   - opts ...google_golang_orggrpc.CallOption
func (_e *PromosClient_Expecter) PromoList(ctx interface{}, in interface{}, opts ...interface{}) *PromosClient_PromoList_Call {
	return &PromosClient_PromoList_Call{Call: _e.mock.On("PromoList",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *PromosClient_PromoList_Call) Run(run func(ctx context.Context, in *grpc.PromoListRequest, opts ...google_golang_orggrpc.CallOption)) *PromosClient_PromoList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]google_golang_orggrpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(google_golang_orggrpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*grpc.PromoListRequest), variadicArgs...)
	})
	return _c
}

func (_c *PromosClient_PromoList_Call) Return(_a0 *grpc.PromosList, _a1 error) *PromosClient_PromoList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PromosClient_PromoList_Call) RunAndReturn(run func(context.Context, *grpc.PromoListRequest, ...google_golang_orggrpc.CallOption) (*grpc.PromosList, error)) *PromosClient_PromoList_Call {
	_c.Call.Return(run)
	return _c
}

// NewPromosClient creates a new instance of PromosClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromosClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromosClient {
	mock := &PromosClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
