// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePromosServer is an autogenerated mock type for the UnsafePromosServer type
type UnsafePromosServer struct {
	mock.Mock
}

type UnsafePromosServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafePromosServer) EXPECT() *UnsafePromosServer_Expecter {
	return &UnsafePromosServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedPromosServer provides a mock function with given fields:
func (_m *UnsafePromosServer) mustEmbedUnimplementedPromosServer() {
	_m.Called()
}

// UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedPromosServer'
type UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedPromosServer is a helper method to define mock.On call
func (_e *UnsafePromosServer_Expecter) mustEmbedUnimplementedPromosServer() *UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call {
	return &UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call{Call: _e.mock.On("mustEmbedUnimplementedPromosServer")}
}

func (_c *UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call) Run(run func()) *UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call) Return() *UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call) RunAndReturn(run func()) *UnsafePromosServer_mustEmbedUnimplementedPromosServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafePromosServer creates a new instance of UnsafePromosServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafePromosServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafePromosServer {
	mock := &UnsafePromosServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
