// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	google_golang_orggrpc "google.golang.org/grpc"

	grpc "grpc/internal/infrastructure/ports/grpc/proto_gen/grpc"

	mock "github.com/stretchr/testify/mock"
)

// UsersClient is an autogenerated mock type for the UsersClient type
type UsersClient struct {
	mock.Mock
}

type UsersClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersClient) EXPECT() *UsersClient_Expecter {
	return &UsersClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *UsersClient) Login(ctx context.Context, in *grpc.UserLoginRequest, opts ...google_golang_orggrpc.CallOption) (*grpc.UserLoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *grpc.UserLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.UserLoginRequest, ...google_golang_orggrpc.CallOption) (*grpc.UserLoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.UserLoginRequest, ...google_golang_orggrpc.CallOption) *grpc.UserLoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.UserLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *grpc.UserLoginRequest, ...google_golang_orggrpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UsersClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *grpc.UserLoginRequest
//   - opts ...google_golang_orggrpc.CallOption
func (_e *UsersClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *UsersClient_Login_Call {
	return &UsersClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *UsersClient_Login_Call) Run(run func(ctx context.Context, in *grpc.UserLoginRequest, opts ...google_golang_orggrpc.CallOption)) *UsersClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]google_golang_orggrpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(google_golang_orggrpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*grpc.UserLoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *UsersClient_Login_Call) Return(_a0 *grpc.UserLoginResponse, _a1 error) *UsersClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersClient_Login_Call) RunAndReturn(run func(context.Context, *grpc.UserLoginRequest, ...google_golang_orggrpc.CallOption) (*grpc.UserLoginResponse, error)) *UsersClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsersClient creates a new instance of UsersClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersClient {
	mock := &UsersClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
