// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"
	grpc "grpc/internal/infrastructure/ports/grpc/proto_gen/grpc"

	mock "github.com/stretchr/testify/mock"
)

// UsersServer is an autogenerated mock type for the UsersServer type
type UsersServer struct {
	mock.Mock
}

type UsersServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersServer) EXPECT() *UsersServer_Expecter {
	return &UsersServer_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *UsersServer) Login(_a0 context.Context, _a1 *grpc.UserLoginRequest) (*grpc.UserLoginResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *grpc.UserLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.UserLoginRequest) (*grpc.UserLoginResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.UserLoginRequest) *grpc.UserLoginResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.UserLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *grpc.UserLoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersServer_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UsersServer_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *grpc.UserLoginRequest
func (_e *UsersServer_Expecter) Login(_a0 interface{}, _a1 interface{}) *UsersServer_Login_Call {
	return &UsersServer_Login_Call{Call: _e.mock.On("Login", _a0, _a1)}
}

func (_c *UsersServer_Login_Call) Run(run func(_a0 context.Context, _a1 *grpc.UserLoginRequest)) *UsersServer_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*grpc.UserLoginRequest))
	})
	return _c
}

func (_c *UsersServer_Login_Call) Return(_a0 *grpc.UserLoginResponse, _a1 error) *UsersServer_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersServer_Login_Call) RunAndReturn(run func(context.Context, *grpc.UserLoginRequest) (*grpc.UserLoginResponse, error)) *UsersServer_Login_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedUsersServer provides a mock function with given fields:
func (_m *UsersServer) mustEmbedUnimplementedUsersServer() {
	_m.Called()
}

// UsersServer_mustEmbedUnimplementedUsersServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedUsersServer'
type UsersServer_mustEmbedUnimplementedUsersServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedUsersServer is a helper method to define mock.On call
func (_e *UsersServer_Expecter) mustEmbedUnimplementedUsersServer() *UsersServer_mustEmbedUnimplementedUsersServer_Call {
	return &UsersServer_mustEmbedUnimplementedUsersServer_Call{Call: _e.mock.On("mustEmbedUnimplementedUsersServer")}
}

func (_c *UsersServer_mustEmbedUnimplementedUsersServer_Call) Run(run func()) *UsersServer_mustEmbedUnimplementedUsersServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UsersServer_mustEmbedUnimplementedUsersServer_Call) Return() *UsersServer_mustEmbedUnimplementedUsersServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UsersServer_mustEmbedUnimplementedUsersServer_Call) RunAndReturn(run func()) *UsersServer_mustEmbedUnimplementedUsersServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsersServer creates a new instance of UsersServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersServer {
	mock := &UsersServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
